spring:
  profiles:
    active: show-usage

logging:
  level:
    root: ERROR
    org:
      springframework: WARN

amqp:
#  uri: amqp://guest:guest@localhost
  host: localhost
  username: guest
  password: guest
  vhost: /
test:
  message: default-message
  nummessages: 1
  delay: 100
  size: -1 #in K bytes
  queue: test.queue