spring:
  profiles:
    active: usage

jms:
  host: localhost
  username: guest
  password: guest
  port: 5672
  ack: AUTO_ACKNOWLEDGE

delay: 0
nummessages: 1
message: default message
queue: test.queue
topic: test.topic
durable: false  #turn on durable subscriber
batchsize: -1 #send and publish


logging:
  level:
    root: ERROR
    org:
      springframework: WARN
#    com:
#      rabbitmq: 
#        jms: TRACE
