#Use the profile to control the role of the application: [send|consume]
spring:
  profiles:
    active: usage #If this is set then show the usage message.

#Properties specific to RabbitMQ/AMQP
amqp:
  uri:
  host: localhost
  username: guest
  password: guest
  port: 5672
  vhost: /
  exchange: #Used by senders/publishers.  amqp.queue | jms.queue are use for routing.
  queue: #Use by consumers (not subscribers)
  ssl: false

#JMS specific properties
jms:
  ack: AUTO_ACKNOWLEDGE
  queue: test.queue
  topic: test.topic
  durable-queue: not-durable  #turn on durable subscriber
  persistent: false
  priority: -1 #no priority set by default
  reply-to:
  ttl: -1

#Properties to control the behavior of the client
delay: 0 #milliseconds between message sends
nummessages: 1
message: default message
message-size: -1 #in characters
batchsize: -1 #turns on transactions
poison:
  send-percent: 0 #percent of messages sent that are poison
  message: ~~Poison~~
  try-limit: 0
  backout-queue: backout.queue
counter: true #senders prepend [c] to a message, cousumers show c in their output

logging:
  level:
    root: ERROR
