#Use the profile to control the role of the application: [send|consume]
spring:
  profiles:
    active: usage #If this is set then show the usage message.

#Properties specific to RabbitMQ/AMQP
amqp:
  uri:
  host: localhost
  username: guest
  password: guest
  port: 5672
  vhost: /
  exchange:
  queue:
  routing-key: #not used

#JMS specific properties
jms:
  ack: AUTO_ACKNOWLEDGE
  queue: test.queue
  topic: test.topic
  durable-queue: not-durable  #turn on durable subscriber
  persitent: false
  priority: -1 #no priority set by default
  reply-to:
  ttl: -1

#Properties to control the behavior of the client
delay: 0 #milliseconds between message sends
nummessages: 1
message: default message
message-size: -1 #not used
batchsize: -1 #turns on transactions
poison:
  enabled: false
  send-percent: 5 #percent of messages sent that are poison
  message: ~~Poison~~

logging:
  level:
    root: ERROR
