spring:
  profiles:
    active: usage

jms:
  host: localhost
  username: guest
  password: guest
  port: 5672
  ack: AUTO_ACKNOWLEDGE

delay: 100
nummessages: 1
message: default message
queue: test.queue
durable: false  #only useful in pub/sub
batchsize: -1


logging:
  level:
    root: ERROR
    org:
      springframework: WARN
#    com:
#      rabbitmq: 
#        jms: TRACE
