spring:
  profiles:
    active: usage

amqp:
  uri: none
  host: localhost
  username: guest
  password: guest
  port: 5672
  vhost: /
  exchange:
  queue:
  routing-key: #not used
jms:
  ack: AUTO_ACKNOWLEDGE
  queue: test.queue
  topic: test.topic
  durable-queue: not-durable  #turn on durable subscriber
  persitent: false

delay: 0
nummessages: 1
message: default message
batchsize: -1 #turn on transactions

logging:
  level:
    root: ERROR
    org:
      springframework: WARN
#    com:
#      rabbitmq: 
#        jms: TRACE
