spring:
  profiles:
    active: usage

jms:
  host: localhost
  username: guest
  password: guest
  port: 5672

delay: 100
nummessages: 1
message: default message
queue: test.queue

logging:
  level:
    root: ERROR
    org:
      springframework: WARN
#    com:
#      rabbitmq: 
#        jms: TRACE
